api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        jsonld: [ 'application/ld+json' ]
        multipart: [ 'multipart/form-data' ]

    defaults:
        stateless: true
        path_prefix: /api
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']