framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
